service: bingebox-serverless
frameworkVersion: "3"
configValidationMode: error

plugins:
  -serverless-webpack

package:
    individually: true

provider:
  name: aws
  runtime: nodejs20.x
  profile: bingeBox-user
  region: eu-north-1
  iam:
    role: arn:aws:iam::497017796861:role/bingeBox-role
  
functions:
# FUNKTIONER TILLHÖRANDE MYLIST

  GETmylist:
    handler: lambdas/endpoints/GETmylist.handler
    events: 
      - httpApi:
          path: /bingebox/mylists
          method: GET    

  POSTmyListItem:
    handler: lambdas/endpoints/POSTmyListItem.handler
    events:
      - httpApi:
          path: /bingebox/mylists
          method: POST

  DELETEmyListItem:
    handler: lambdas/endpoints/DELETEmyListItem.handler
    events:
      - httpApi:
          path: /bingebox/mylists
          method: DELETE

# FUNKTIONER TILLHÖRANDE WATCHEDLIST

  GETwatchedlist:
    handler: lambdas/endpoints/GETwatchedlist.handler
    events: 
      - httpApi:
          path: /bingebox/watchedlists
          method: GET    

  POSTwatchedListItem:
    handler: lambdas/endpoints/POSTwatchedListItem.handler
    events:
      - httpApi:
          path: /bingebox/watchedlists
          method: POST

  DELETEwatchedListItem:
    handler: lambdas/endpoints/DELETEwatchedListItem.handler
    events:
      - httpApi:
          path: /bingebox/watchedlists
          method: DELETE

  LOGINAuth:
    handler: lambdas/endpoints/LOGINAuth.handler
    events:
      - httpApi:
          path: /bingebox/login
          method: POST

resources:
  Resources:      
    MyListTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: MyListTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: false
        KeySchema:
          - AttributeName: userId
            KeyType: HASH


    WatchedListTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: WatchedListTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: false
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
    
    UserTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: UserTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: false
        KeySchema:
          - AttributeName: email
            KeyType: HASH

    
        

      
  
