service: bingebox-serverless
frameworkVersion: "3"
configValidationMode: error

plugins:
  -serverless-webpack

package:
    individually: true

provider:
  name: aws
  runtime: nodejs20.x
  profile: bingeBox-user
  region: eu-north-1
  iam:
    role: arn:aws:iam::497017796861:role/bingeBox-role
  
functions:
# FUNKTIONER TILLHÖRANDE MYLIST

  GETmylist:
    handler: lambdas/endpoints/GETmylist.handler
    events: 
      - httpApi:
          path: /bingebox/mylists
          method: GET    

  POSTmyListItem:
    handler: lambdas/endpoints/POSTmyListItem.handler
    events:
      - httpApi:
          path: /bingebox/mylists
          method: POST

  DELETEmyListItem:
    handler: lambdas/endpoints/DELETEmyListItem.handler
    events:
      - httpApi:
          path: /bingebox/mylists
          method: DELETE

# FUNKTIONER TILLHÖRANDE WATCHEDLIST

  GETwatchedlist:
    handler: lambdas/endpoints/GETwatchedlist.handler
    events: 
      - httpApi:
          path: /bingebox/watchedlists
          method: GET    

  POSTwatchedListItem:
    handler: lambdas/endpoints/POSTwatchedListItem.handler
    events:
      - httpApi:
          path: /bingebox/watchedlists
          method: POST

  DELETEwatchedListItem:
    handler: lambdas/endpoints/DELETEwatchedListItem.handler
    events:
      - httpApi:
          path: /bingebox/watchedlists
          method: DELETE

resources:
  Resources:      
    MyListTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: MyListTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: false
        KeySchema:
          - AttributeName: userId
            KeyType: HASH


    WatchedListTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: WatchedListTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: false
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
         
     
    # userListTable:
    #   Type: AWS::DynamoDB::Table
    #   DeletionPolicy: Retain
    #   Properties:
    #     TableName: userListTable
    #     AttributeDefinitions:
    #       - AttributeName: "userId"
    #         AttributeType: "S"
    #       - AttributeName: "listType"
    #         AttributeType: "S"
    #     BillingMode: PAY_PER_REQUEST
    #     PointInTimeRecoverySpecification:
    #       PointInTimeRecoveryEnabled: false
    #     KeySchema:
    #       - AttributeName: "userId"
    #         KeyType: HASH
    #       - AttributeName: "listType"
    #         KeyType: RANGE
        
    # CognitoUserPool:
    #   Type: AWS::Cognito::UserPool
    #   Properties: 
    #     UserPoolName: ${self:provider.stage}-user-pool
    #     UsernameAttributes:
    #       - email
    #     AutoVerifiedAttributes:
    #       - email  
    # CognitoUserPoolClient:
    #   Type: AWS::Cognito::UserPoolClient
    #   Properties:
    #     ClientName: ${self:provider.stage}-user-pool-client
    #     UserPoolId:
    #       Ref: CognitoUserPool
    #     ExplicitAuthFlows:
    #       - ADMIN_NO_SRP_AUTH
    #     GenerateSecret: false

    
        

      
  
